import type { PageGuide } from "@/types/aide";

/** Guides par tâche — module « Coûts, locations et facturation » (2026-09-29). */
export const guidesCouts: PageGuide[] = [
  {
    type: "GUIDE",
    id: "guide-saisir-couts-vehicule",
    titre: "Saisir les coûts fixes d'un véhicule",
    resume: "Renseigner l'achat ou la location, l'amortissement, l'assurance, les taxes et la vignette d'un véhicule.",
    revision: "2026-09-29",
    motsCles: ["coût", "achat", "prix", "amortissement", "valeur résiduelle", "assurance", "taxe", "vignette", "crédit-bail", "location longue durée", "tco"],
    ecrans: ["/engins/:id/fiche"],
    capacite: "GERER_PARC",
    frequence: "OCCASIONNELLE",
    priorite: "HAUTE",
    objectif: "Connaître le coût complet (TCO) d'un véhicule, pas seulement son carburant et sa maintenance.",
    etapes: [
      "Ouvrez la fiche du véhicule, puis cliquez sur la rubrique **Coûts**.",
      "Choisissez le **Mode d'acquisition** : achat, location longue durée ou crédit-bail.",
      "Pour un achat, saisissez le prix, la durée d'amortissement en mois et la valeur résiduelle.",
      "Pour une location, saisissez le **Loyer mensuel**.",
      "Saisissez les charges annuelles : assurance, taxes, vignette, autres.",
      "Cliquez sur **Enregistrer les coûts**.",
    ],
    resultat: "L'amortissement mensuel, la valeur nette et les charges annuelles s'affichent ; le véhicule entre dans le coût complet.",
    bonASavoir: [
      "L'amortissement est linéaire, à partir de la date d'acquisition si vous ne donnez pas d'autre date.",
      "Les pneus se suivent en maintenance, sur le poste « Remplacement des pneus ».",
    ],
    voirAussi: ["guide-suivre-couts-complets"],
  },
  {
    type: "GUIDE",
    id: "guide-suivre-couts-complets",
    titre: "Suivre le coût complet (TCO) et les véhicules à problèmes",
    resume: "Voir ce que coûte vraiment chaque véhicule et lesquels surveiller ou remplacer.",
    revision: "2026-09-29",
    motsCles: ["tco", "coût complet", "coût total de possession", "rentabilité", "à remplacer", "à surveiller", "pannes", "véhicule problématique"],
    ecrans: ["/couts"],
    capacite: "CONSULTER_GESTION",
    frequence: "MENSUELLE",
    priorite: "HAUTE",
    objectif: "Décider quels véhicules garder, surveiller ou remplacer, chiffres à l'appui.",
    etapes: [
      "Ouvrez le menu **Pilotage**, puis cliquez sur **Coûts**.",
      "Dans l'onglet **Coût complet (TCO)**, choisissez la période, par exemple **Cette année**.",
      "Lisez le coût par poste, puis les tableaux par type et par véhicule.",
      "Cliquez sur **Coûts fixes à saisir** sous un véhicule pour compléter sa fiche.",
      "Ouvrez l'onglet **Véhicules à problèmes** et cliquez sur **À remplacer**.",
      "Cliquez sur **Rapport PDF (tout le parc)** pour garder le résultat.",
    ],
    resultat: "Vous voyez le coût complet de chaque véhicule et la liste motivée des véhicules à surveiller ou à remplacer.",
    bonASavoir: [
      "Coût complet = carburant, maintenance, location entrante, incidents, plus amortissement ou loyers, assurance, taxes et vignette.",
      "À surveiller ou à remplacer : coût de maintenance au km comparé à la moyenne du type, pannes sur 12 mois, âge, compteur.",
      "Les seuils se règlent dans **Paramètres** (Administrateur, Directeur général, Responsable du parc).",
    ],
    voirAussi: ["guide-saisir-couts-vehicule", "guide-suivre-budget-carburant"],
  },
  {
    type: "GUIDE",
    id: "guide-suivre-budget-carburant",
    titre: "Fixer et suivre le budget carburant",
    resume: "Prévoir la dépense carburant de l'année par type de véhicule et comprendre les écarts.",
    revision: "2026-09-29",
    motsCles: ["budget", "carburant", "prévisionnel", "réel", "écart", "dépassement", "projection", "gasoil", "prix du litre"],
    ecrans: ["/couts"],
    capacite: "CONSULTER_GESTION",
    frequence: "MENSUELLE",
    priorite: "MOYENNE",
    objectif: "Savoir si la dépense carburant tient le budget, et pourquoi elle s'en écarte.",
    avantDeCommencer: ["Fixer un budget demande le rôle Directeur général ou Responsable du parc."],
    etapes: [
      "Ouvrez **Coûts**, puis l'onglet **Budget carburant**.",
      "Cliquez sur **Nouveau budget** et choisissez le type de véhicule.",
      "Saisissez les km (ou heures) prévus, la consommation prévue et le prix du litre.",
      "Cochez **Répartir selon les mois** si la dépense varie selon la saison.",
      "Cliquez sur **Enregistrer**.",
      "Chaque mois, lisez l'écart, sa cause principale et la projection de fin d'année.",
    ],
    resultat: "Le budget à date est comparé à la dépense réelle, avec l'écart expliqué par les km, la consommation et le prix du litre.",
    bonASavoir: [
      "La somme des trois effets est exactement égale à l'écart.",
      "La projection prolonge le rythme actuel en tenant compte de la répartition mensuelle.",
    ],
    voirAussi: ["guide-suivre-couts-complets"],
  },
  {
    type: "GUIDE",
    id: "guide-recevoir-rapports-email",
    titre: "Recevoir des rapports par e-mail",
    resume: "Recevoir chaque semaine ou chaque mois les rapports PDF de votre choix, sans rien générer.",
    revision: "2026-09-29",
    motsCles: ["e-mail", "email", "mail", "abonnement", "envoi automatique", "synthèse mensuelle", "hebdomadaire", "mensuel", "pdf", "dg"],
    ecrans: ["/rapports", "/parametres"],
    capacite: "CONSULTER_GESTION",
    frequence: "OCCASIONNELLE",
    priorite: "HAUTE",
    objectif: "Recevoir la synthèse du parc dans sa boîte mail, à date fixe.",
    avantDeCommencer: ["Votre compte doit avoir une adresse e-mail valide.", "La messagerie du serveur doit être configurée par l'administrateur."],
    etapes: [
      "Ouvrez le menu **Pilotage**, puis cliquez sur **Rapports**.",
      "Cliquez sur **Recevoir par e-mail**.",
      "Activez les rapports voulus dans la colonne **Chaque semaine** ou **Chaque mois**.",
      "Lisez la date du prochain envoi sous le tableau.",
      "Cliquez sur **Envoyer maintenant** pour recevoir tout de suite la période écoulée.",
    ],
    resultat: "Vous recevez un seul e-mail par période, avec un PDF par rapport choisi.",
    bonASavoir: [
      "L'e-mail hebdomadaire couvre la semaine écoulée (lundi à dimanche) ; le mensuel, le mois écoulé.",
      "Le jour et l'heure des envois se règlent dans **Paramètres**, rubrique « Rapports par e-mail ».",
      "L'administration peut gérer les abonnements d'un autre utilisateur depuis la même fenêtre.",
      "Un envoi manqué part au redémarrage du serveur ; les échecs apparaissent dans « Derniers envois ».",
    ],
    voirAussi: ["guide-generer-rapport"],
  },
  {
    type: "GUIDE",
    id: "guide-anticiper-previsions",
    titre: "Anticiper les dépenses et les km avec les prévisions",
    resume: "Lire la tendance des 24 derniers mois et la projection des 12 prochains, pour tout le parc ou un type.",
    revision: "2026-09-29",
    motsCles: ["prévision", "projection", "tendance", "moyenne mobile", "budget", "fin d'année", "kilomètres", "heures", "anticiper"],
    ecrans: ["/couts"],
    capacite: "CONSULTER_GESTION",
    frequence: "MENSUELLE",
    priorite: "MOYENNE",
    objectif: "Préparer le budget et repérer à temps une dérive des dépenses ou de l'activité.",
    etapes: [
      "Ouvrez **Coûts**, puis l'onglet **Prévisions**.",
      "Choisissez **Tout le parc** ou un type de véhicule.",
      "Lisez la tendance des dépenses et la projection des 12 prochains mois.",
      "Cliquez sur **Carburant**, **Kilomètres** ou **Heures moteur** pour changer de courbe.",
      "Comparez la dépense carburant prévue à fin d'année au budget.",
    ],
    resultat: "Vous savez si les dépenses montent ou baissent, et où elles devraient finir l'année.",
    bonASavoir: [
      "Barres pleines : réel ; barres claires : projection ; ligne : moyenne des 3 derniers mois.",
      "Il faut au moins 3 mois complets d'activité pour projeter.",
      "Les saisons ne sont pas prises en compte : la projection reste une indication.",
    ],
    voirAussi: ["guide-suivre-budget-carburant", "guide-suivre-couts-complets"],
  },
  {
    type: "GUIDE",
    id: "guide-exporter-ecritures",
    titre: "Exporter les écritures pour la comptabilité",
    resume: "Télécharger un fichier CSV d'écritures (factures, carburant, maintenance) à importer dans le logiciel comptable.",
    revision: "2026-09-29",
    motsCles: ["comptabilité", "comptable", "export", "csv", "écritures", "journal", "compte", "débit", "crédit", "factures", "intégration comptable"],
    ecrans: ["/export-comptable"],
    capacite: "CONSULTER_GESTION",
    frequence: "MENSUELLE",
    priorite: "MOYENNE",
    objectif: "Passer les opérations du parc en comptabilité sans ressaisie.",
    avantDeCommencer: ["Les journaux et les comptes doivent être validés par le comptable dans **Paramètres**, rubrique « Export comptable »."],
    etapes: [
      "Ouvrez le menu **Finances**, puis cliquez sur **Export comptable**.",
      "Choisissez la période, par exemple **Mois dernier**.",
      "Cochez les opérations à exporter.",
      "Vérifiez l'aperçu : totaux par journal et mention « Chaque pièce est équilibrée ».",
      "Cliquez sur **Télécharger le CSV**, puis importez-le dans votre logiciel comptable.",
    ],
    resultat: "Le fichier contient une ligne par écriture : date, journal, pièce, compte, libellé, débit, crédit, véhicule et tiers.",
    bonASavoir: [
      "Les factures annulées ne sont pas exportées ; les opérations sans montant sont signalées dans l'aperçu.",
      "Le centre de coût est le véhicule : l'analytique par véhicule se fait dans le logiciel comptable.",
      "Séparateur point-virgule : virgule décimale, prêt pour Excel en français.",
    ],
    voirAussi: ["guide-suivre-couts-complets"],
  },
];
