import type { PageGuide } from "@/types/aide";
import { REVISION_INITIALE } from "@/features/aide/contenu/revision";

/** Guides par tâche — module « Maintenance ». */
export const guidesMaintenance: PageGuide[] = [
  {
    type: "GUIDE",
    id: "guide-creer-maintenance",
    titre: "Créer une maintenance",
    resume: "Commencer tout de suite ou planifier une intervention sur un véhicule.",
    revision: REVISION_INITIALE,
    motsCles: ["entretien", "réparation", "vidange", "garage", "atelier", "intervention", "révision"],
    ecrans: ["/maintenance", "/engins/:id/rapport"],
    capacite: "GERER_MAINTENANCE",
    frequence: "HEBDOMADAIRE",
    priorite: "HAUTE",
    objectif: "Enregistrer une intervention et immobiliser le véhicule le temps des travaux.",
    avantDeCommencer: ["Avoir le rôle Chef de maintenance, Responsable du parc ou Directeur général."],
    etapes: [
      "Ouvrez le menu **Atelier**, puis cliquez sur **Maintenance**.",
      "Cliquez sur **Nouvelle maintenance**, puis choisissez le véhicule.",
      "Cochez les **Travaux à faire**.",
      "Choisissez l'**Atelier** : **Atelier interne** ou un garage externe.",
      "Choisissez **Commencer maintenant** ou **Planifier**, avec une **Date prévue (optionnel)**.",
      "Cliquez sur **Commencer la maintenance** ou **Planifier la maintenance**.",
    ],
    resultat: "La maintenance apparaît « En cours » (véhicule en maintenance) ou « Planifiée ».",
    bonASavoir: [
      "Depuis le rapport d'un véhicule, **Faire la maintenance** ouvre le même formulaire, véhicule déjà choisi.",
      "Des avertissements s'affichent si le véhicule a déjà une maintenance ou une mission.",
    ],
    schema: "circuit-maintenance",
    captures: [
      { fichier: "maintenance-nouvelle-01.png", alt: "Formulaire de maintenance avec les travaux cochés et le choix Commencer maintenant ou Planifier", legende: "Le formulaire unique de maintenance." },
    ],
    voirAussi: ["guide-terminer-maintenance", "guide-replanifier-maintenance", "reference-maintenance"],
  },
  {
    type: "GUIDE",
    id: "guide-replanifier-maintenance",
    titre: "Replanifier une maintenance",
    resume: "Changer ou retirer la date prévue d'une maintenance planifiée.",
    revision: REVISION_INITIALE,
    motsCles: ["reporter", "décaler", "date prévue", "changer la date", "planning"],
    ecrans: ["/maintenance"],
    capacite: "GERER_MAINTENANCE",
    frequence: "HEBDOMADAIRE",
    priorite: "MOYENNE",
    objectif: "Garder un planning juste quand une intervention est décalée.",
    etapes: [
      "Ouvrez **Maintenance**.",
      "Cliquez sur la ligne de la maintenance planifiée pour ouvrir sa fiche.",
      "Cliquez sur **Replanifier**.",
      "Choisissez la **Nouvelle date prévue** et, si besoin, un **Motif (optionnel)**.",
      "Cliquez sur **Replanifier**.",
    ],
    resultat: "La nouvelle date s'affiche dans la liste et dans le planning des véhicules.",
    bonASavoir: [
      "Une date passée est refusée.",
      "**Retirer la date** garde la maintenance planifiée, sans date.",
      "Le changement et son motif sont notés dans le journal d'audit.",
    ],
    voirAussi: ["depannage-date-maintenance-passee", "guide-creer-maintenance"],
  },
  {
    type: "GUIDE",
    id: "guide-terminer-maintenance",
    titre: "Terminer une maintenance",
    resume: "Clôturer une intervention, avec les pièces, le proforma du garage et le contrôle qualité.",
    revision: "2026-09-29",
    motsCles: ["clôturer maintenance", "fin des travaux", "proforma", "pièces", "coût", "contrôle qualité", "essai", "réserve"],
    ecrans: ["/maintenance"],
    capacite: "GERER_MAINTENANCE",
    frequence: "HEBDOMADAIRE",
    priorite: "HAUTE",
    objectif: "Rendre le véhicule disponible et figer le coût de l'intervention.",
    avantDeCommencer: ["Pour un garage externe : avoir le proforma du garage (PDF ou photo)."],
    etapes: [
      "Ouvrez **Maintenance**, puis cliquez sur la ligne pour ouvrir la fiche.",
      "Ajoutez les pièces du stock avec **Ajouter une pièce**, si besoin.",
      "Cliquez sur **Terminer**.",
      "Indiquez la **Prochaine date d'entretien (optionnel)**.",
      "Pour un garage externe, joignez le **Proforma du garage externe**.",
      "Dans **Contrôle qualité**, saisissez **Contrôlé par** et activez **Essai concluant**.",
      "Notez une **Réserve** si un point reste à surveiller.",
      "Cliquez sur **Terminer**.",
    ],
    resultat: "La maintenance passe « Terminée » ; son coût total et son contrôle qualité sont enregistrés.",
    bonASavoir: [
      "Sans proforma, une maintenance chez un garage externe ne peut pas être terminée.",
      "Si l'essai n'est pas concluant, laissez la maintenance en cours : elle ne peut pas être terminée.",
      "Une réserve crée une alerte « Réserve au contrôle qualité ».",
      "Une maintenance terminée ne peut plus être modifiée.",
    ],
    schema: "circuit-maintenance",
    voirAussi: ["depannage-terminer-bloque", "guide-creer-maintenance", "guide-suivre-fiabilite"],
  },
  {
    type: "GUIDE",
    id: "guide-suivre-fiabilite",
    titre: "Suivre la fiabilité et le planning d'entretien",
    resume: "Voir les pannes, les immobilisations et leur coût, les délais de réparation et les entretiens en retard.",
    revision: "2026-09-29",
    motsCles: ["fiabilité", "panne", "mtbf", "mttr", "immobilisation", "disponibilité", "délai de réparation", "garage", "entretien en retard", "planning", "contrôle qualité"],
    ecrans: ["/fiabilite"],
    capacite: "CONSULTER_GESTION",
    frequence: "MENSUELLE",
    priorite: "HAUTE",
    objectif: "Réduire les pannes et les immobilisations, et faire les entretiens à temps.",
    etapes: [
      "Ouvrez le menu **Pilotage**, puis cliquez sur **Fiabilité et conformité**.",
      "Dans l'onglet **Fiabilité et entretien**, choisissez la période, par exemple **Cette année**.",
      "Lisez la disponibilité, les jours d'immobilisation et leur coût.",
      "Comparez le délai de réparation de l'atelier interne et des garages.",
      "Traitez les lignes **À faire** du tableau **Respect du planning d'entretien**.",
      "Cliquez sur **Réglages par type** pour chiffrer une journée d'immobilisation.",
    ],
    resultat: "Vous savez quels véhicules tombent en panne, combien coûtent leurs arrêts et quels entretiens sont en retard.",
    bonASavoir: [
      "Temps moyen entre pannes = jours dans le parc ÷ pannes (incidents « Panne » ou réparations correctives, le plus grand des deux).",
      "Un entretien est à temps s'il est fait au plus 7 jours ou 5 % de l'intervalle après l'échéance.",
      "Les véhicules qui tombent souvent en panne remontent dans le plan de **Renouvellement**.",
    ],
    voirAussi: ["guide-terminer-maintenance", "guide-planifier-renouvellement"],
  },
];
