import type { PageGuide } from "@/types/aide";
import { REVISION_INITIALE } from "@/features/aide/contenu/revision";

/** Guides par tâche — module « Rapports, messagerie et administration ». */
export const guidesPilotage: PageGuide[] = [
  {
    type: "GUIDE",
    id: "guide-suivre-performance",
    titre: "Suivre la performance et l'utilisation du parc",
    resume: "Voir le taux d'utilisation réel, les véhicules sous-utilisés ou en trop et le coût par km ou par heure.",
    revision: "2026-09-28",
    motsCles: [
      "performance", "utilisation", "taux", "sous-utilisé", "redondant", "en trop", "coût par km", "coût par heure",
      "kpi", "indicateur", "objectif", "benchmark", "référence", "rentabilité",
    ],
    ecrans: ["/performance"],
    capacite: "CONSULTER_GESTION",
    frequence: "MENSUELLE",
    priorite: "HAUTE",
    objectif: "Savoir quels véhicules servent vraiment, lesquels coûtent trop cher et si les objectifs du parc sont atteints.",
    avantDeCommencer: [
      "Pour être évalués, les types de véhicule doivent avoir leurs seuils et leur coût de référence.",
    ],
    etapes: [
      "Ouvrez le menu **Pilotage**, puis cliquez sur **Performance**.",
      "Choisissez la période, par exemple **Mois dernier**.",
      "Lisez les cartes **KPI du parc** : valeur, objectif et statut.",
      "Regardez le tableau **Par type de véhicule** : coût unitaire, écart à la référence, véhicules en trop.",
      "Dans **Par véhicule**, cliquez sur **Sous-utilisés** pour voir les véhicules concernés et leurs motifs.",
      "Cliquez sur **Rapport PDF (tout le parc)** pour garder ou partager le résultat.",
    ],
    resultat: "Vous savez quels véhicules vendre, restituer, transférer ou mieux employer, et quels coûts surveiller.",
    bonASavoir: [
      "Un jour est « utilisé » s'il y a une mission, un trajet GPS ou un plein.",
      "Km : le plus grand entre les relevés (missions, pleins) et la distance GPS. Heures : compteur horaire saisi.",
      "Coûts : carburant, maintenance terminée, location entrante au prorata, coût estimé des incidents.",
      "Vert : coût égal ou inférieur à la référence ; orange : jusqu'à +10 % ; rouge : au-delà.",
      "« En trop » : véhicules au-delà du plus grand nombre du même type utilisés le même jour. À confirmer.",
      "Le bouton crayon d'une carte KPI règle son objectif (Directeur général, Responsable parc).",
    ],
    voirAussi: ["guide-regler-seuils-type", "guide-generer-rapport"],
  },
  {
    type: "GUIDE",
    id: "guide-regler-seuils-type",
    titre: "Régler les seuils de sous-utilisation et le coût de référence",
    resume: "Dire, pour chaque type de véhicule, à partir de quand il est sous-utilisé et combien il devrait coûter.",
    revision: "2026-09-28",
    motsCles: ["seuil", "sous-utilisation", "coût de référence", "benchmark", "type de véhicule", "km par mois", "heures par mois"],
    ecrans: ["/types-engin", "/performance"],
    capacite: "GERER_PARC",
    frequence: "OCCASIONNELLE",
    priorite: "MOYENNE",
    objectif: "Adapter l'analyse de performance à chaque type : un camion et une pelle ne s'utilisent pas pareil.",
    etapes: [
      "Ouvrez le menu **Parc**, puis cliquez sur **Types de véhicule**.",
      "Dans le menu **…** du type, cliquez sur **Modifier**.",
      "Saisissez le **Seuil d'utilisation (% des jours)**, par exemple 50.",
      "Saisissez le **Seuil d'usage** : km par mois pour un véhicule routier, heures par mois pour un engin.",
      "Saisissez le **Coût de référence** en Ar par km ou par heure.",
      "Cliquez sur **Enregistrer**.",
    ],
    resultat: "La page **Performance** classe les véhicules de ce type et colore leur coût unitaire.",
    bonASavoir: [
      "Un véhicule est sous-utilisé si l'un des deux seuils n'est pas atteint.",
      "Champ vide : le critère n'est pas contrôlé. Aucun seuil : le type est « Non évalué ».",
      "Pour les engins de chantier, saisissez le compteur horaire à chaque plein et en début et fin de mission.",
    ],
    voirAussi: ["guide-suivre-performance"],
  },
  {
    type: "GUIDE",
    id: "guide-generer-rapport",
    titre: "Générer un rapport et le télécharger en PDF",
    resume: "Produire une synthèse chiffrée (parc, véhicule, conducteur, carburant…) et l'enregistrer.",
    revision: REVISION_INITIALE,
    motsCles: ["rapport", "pdf", "excel", "exporter", "synthèse", "bilan", "statistiques", "imprimer"],
    ecrans: ["/rapports"],
    capacite: "CONSULTER_GESTION",
    frequence: "HEBDOMADAIRE",
    priorite: "HAUTE",
    objectif: "Obtenir un document clair à partager ou à imprimer.",
    etapes: [
      "Ouvrez le menu **Pilotage**, puis cliquez sur **Rapports**.",
      "Cliquez sur **Nouveau rapport**.",
      "Cliquez sur la carte du rapport voulu, par exemple **Synthèse générale**.",
      "Choisissez la période, par exemple **Ce mois**.",
      "Choisissez le véhicule, le conducteur ou le chantier si le rapport le demande.",
      "Cliquez sur **Générer le rapport**.",
      "Dans l'aperçu, cliquez sur **Télécharger le PDF** ou sur **Excel**.",
    ],
    resultat: "Le fichier est enregistré sur votre ordinateur ; le rapport reste dans la liste.",
    bonASavoir: [
      "L'aperçu montre exactement le contenu du PDF.",
      "**Régénérer** refait le même rapport avec les chiffres d'aujourd'hui.",
    ],
    captures: [
      { fichier: "rapports-catalogue-01.png", alt: "Choix du type de rapport présenté en cartes rangées par famille", legende: "Le catalogue des rapports." },
      { fichier: "rapports-apercu-02.png", alt: "Aperçu d'un rapport avec chiffres clés en cartes colorées et boutons de téléchargement", legende: "L'aperçu et les boutons de téléchargement." },
    ],
    voirAussi: ["reference-pilotage", "guide-recevoir-rapports-email"],
  },
  {
    type: "GUIDE",
    id: "guide-envoyer-message",
    titre: "Envoyer un message à un collègue",
    resume: "Écrire à une personne ou discuter d'un véhicule avec la messagerie interne.",
    revision: REVISION_INITIALE,
    motsCles: ["message", "discussion", "chat", "écrire", "contacter", "photo", "pièce jointe"],
    ecrans: ["/messagerie"],
    frequence: "QUOTIDIENNE",
    priorite: "MOYENNE",
    objectif: "Échanger sans quitter l'application, avec l'historique au même endroit.",
    etapes: [
      "Cliquez sur **Messagerie** dans la barre en bas de l'écran.",
      "Cliquez sur **Nouveau message**.",
      "Cherchez la personne par son nom ou son rôle, puis cliquez dessus.",
      "Écrivez votre message, puis appuyez sur **Entrée** pour l'envoyer.",
    ],
    resultat: "Le message apparaît dans la conversation ; la personne voit une pastille de message non lu.",
    bonASavoir: [
      "Joignez une photo ou un PDF avec le bouton trombone.",
      "Le bouton **Discussion** d'un véhicule ou d'une mission ouvre une conversation liée à cet objet.",
    ],
    voirAussi: ["contact-support"],
  },
  {
    type: "GUIDE",
    id: "guide-creer-utilisateur",
    titre: "Créer un compte utilisateur",
    resume: "Donner accès à l'application à une nouvelle personne, avec le bon rôle.",
    revision: REVISION_INITIALE,
    motsCles: ["compte", "utilisateur", "accès", "mot de passe", "rôle", "nouvel employé"],
    ecrans: ["/utilisateurs"],
    capacite: "ADMINISTRER",
    frequence: "MENSUELLE",
    priorite: "HAUTE",
    objectif: "Permettre à un nouvel utilisateur de se connecter en moins de 5 minutes.",
    etapes: [
      "Ouvrez le menu **Administration**, puis cliquez sur **Utilisateurs**.",
      "Cliquez sur **Nouvel utilisateur**.",
      "Saisissez le **Nom**, le **Prénom** et l'**Email**.",
      "Choisissez un **Mot de passe** provisoire.",
      "Choisissez le **Rôle**.",
      "Cliquez sur **Créer**.",
    ],
    resultat: "La personne peut se connecter avec son email et ce mot de passe.",
    bonASavoir: [
      "Transmettez le mot de passe de vive voix, jamais par un canal public.",
      "Seuls un Directeur général ou un Administrateur attribuent ces deux rôles.",
      "Pour retirer l'accès, désactivez le compte au lieu de le supprimer.",
    ],
    voirAussi: ["demarrer-roles", "depannage-identifiants"],
  },
  {
    type: "GUIDE",
    id: "guide-regler-controles",
    titre: "Régler le contrôle de consommation et l'escalade des alertes",
    resume: "Choisir le seuil d'alerte de consommation et les délais de montée des alertes.",
    revision: REVISION_INITIALE,
    motsCles: ["paramètres", "seuil", "tolérance", "escalade", "délai", "consommation anormale", "réglages"],
    ecrans: ["/parametres"],
    capacite: "ADMINISTRER",
    frequence: "OCCASIONNELLE",
    priorite: "BASSE",
    objectif: "Adapter les alertes à la réalité de votre parc.",
    etapes: [
      "Cliquez sur votre avatar dans la barre en bas, puis sur **Paramètres**.",
      "Dans **Contrôle de consommation carburant**, réglez le **Dépassement toléré (%)** et la **Tolérance (litres)**.",
      "Cliquez sur **Enregistrer**.",
      "Dans **Escalade des alertes non traitées**, cochez **Activer l'escalade** et réglez les délais.",
      "Cliquez sur **Enregistrer**.",
    ],
    resultat: "Les nouvelles règles s'appliquent aux prochaines saisies et au prochain contrôle horaire.",
    bonASavoir: [
      "Un délai de 0 jour empêche une alerte de monter depuis ce niveau.",
      "La consommation de référence d'un véhicule se règle dans sa fiche technique.",
    ],
    voirAussi: ["faq-consommation-anormale", "faq-alerte-monte"],
  },
];
