import type { PageGuide } from "@/types/aide";
import { REVISION_INITIALE } from "@/features/aide/contenu/revision";

/** Guides par tâche — module « GPS, zones et alertes ». */
export const guidesSuivi: PageGuide[] = [
  {
    type: "GUIDE",
    id: "guide-score-conduite",
    titre: "Suivre le score de conduite des conducteurs",
    resume: "Voir chaque mois qui conduit prudemment et qui a besoin d'une formation.",
    revision: "2026-09-29",
    motsCles: ["conduite", "score", "survitesse", "freinage brusque", "accélération", "virage", "comportement", "formation", "sécurité"],
    ecrans: ["/couts"],
    capacite: "CONSULTER_GESTION",
    frequence: "MENSUELLE",
    priorite: "MOYENNE",
    objectif: "Repérer les conduites à risque pour réduire accidents, usure et consommation.",
    avantDeCommencer: ["Les véhicules doivent avoir un boîtier GPS ; les conducteurs, des missions ou des affectations."],
    etapes: [
      "Ouvrez **Coûts**, puis l'onglet **Conduite**.",
      "Choisissez le mois.",
      "Lisez le score de chaque conducteur, du plus faible au plus élevé.",
      "Regardez le détail : survitesses, accélérations, freinages et virages brusques.",
      "Planifiez un entretien ou une formation pour les conducteurs « À former ».",
    ],
    resultat: "Vous savez quels conducteurs accompagner en priorité.",
    bonASavoir: [
      "Score = 100 − 5 × points pour 100 km ; survitesse 3 points, manœuvre brusque 2 points.",
      "Un événement est attribué au conducteur de la mission en cours, sinon à celui de l'affectation.",
      "Les manœuvres brusques viennent de Traccar, si les boîtiers les détectent ; sinon seule la survitesse compte.",
    ],
    voirAussi: ["guide-suivre-vehicule-carte"],
  },
  {
    type: "GUIDE",
    id: "guide-suivre-vehicule-carte",
    titre: "Suivre un véhicule sur la carte GPS",
    resume: "Voir où se trouve un véhicule, sa vitesse, son chantier et son trajet.",
    revision: "2026-09-30",
    motsCles: ["gps", "carte", "position", "localisation", "où est", "trajet", "suivi en direct", "chantier"],
    ecrans: ["/gps", "/engins/:id/rapport"],
    frequence: "QUOTIDIENNE",
    priorite: "HAUTE",
    objectif: "Localiser un véhicule en quelques secondes.",
    avantDeCommencer: ["Le véhicule est équipé d'un boîtier GPS actif."],
    etapes: [
      "Ouvrez le menu **Exploitation**, puis cliquez sur **GPS & trajets**.",
      "Restez sur l'onglet **Carte** : chaque point est un véhicule.",
      "Cliquez sur un point : véhicule, heure, vitesse, et s'il est sur son chantier.",
      "Pour un seul véhicule, ouvrez son rapport et regardez la carte **Localisation**.",
    ],
    resultat: "Vous voyez la dernière position du véhicule, son chantier du jour et, dans son rapport, son trajet des 24 dernières heures.",
    bonASavoir: [
      "Les positions se mettent à jour toutes les 30 secondes.",
      "Sans transmission depuis plus d'une heure, la position est signalée « ancienne ».",
      "Couleur du point : vert disponible, bleu en mission, orange en maintenance, rouge en panne.",
    ],
    voirAussi: ["guide-chantiers-carte-gps", "depannage-pas-de-position", "guide-installer-boitier-gps"],
  },
  {
    type: "GUIDE",
    id: "guide-installer-boitier-gps",
    titre: "Installer un boîtier GPS sur un véhicule",
    resume: "Relier un boîtier GPS à un véhicule pour recevoir ses positions.",
    revision: REVISION_INITIALE,
    motsCles: ["boîtier", "traceur", "dispositif", "traccar", "installer gps"],
    ecrans: ["/gps"],
    capacite: "GERER_PARC",
    frequence: "OCCASIONNELLE",
    priorite: "BASSE",
    objectif: "Suivre un véhicule sur la carte dès qu'il roule.",
    avantDeCommencer: ["Noter le numéro de série inscrit sur le boîtier."],
    etapes: [
      "Ouvrez **GPS & trajets**, puis l'onglet **Dispositifs**.",
      "Cliquez sur **Installer un dispositif**.",
      "Saisissez le **Numéro de série** et choisissez le **Véhicule**.",
      "Indiquez la **Date d'installation**.",
      "Cliquez sur **Installer**.",
    ],
    resultat: "Le boîtier apparaît « Actif » ; le véhicule s'affiche sur la carte dès la première position reçue.",
    bonASavoir: [
      "Un véhicule n'a qu'un boîtier à la fois.",
      "Avec Traccar, le numéro de série doit être identique à l'identifiant du boîtier dans Traccar.",
    ],
    voirAussi: ["guide-suivre-vehicule-carte", "reference-suivi"],
  },
  {
    type: "GUIDE",
    id: "guide-traiter-alerte",
    titre: "Traiter une alerte",
    resume: "Lire une alerte, régler sa cause, puis la laisser se fermer seule ou la marquer comme traitée.",
    revision: "2026-09-30",
    motsCles: ["alerte", "notification", "avertissement", "critique", "escalade", "priorité", "close auto", "vérifier les causes"],
    ecrans: ["/alertes", "/"],
    capacite: "GERER_PARC",
    frequence: "QUOTIDIENNE",
    priorite: "HAUTE",
    objectif: "Ne laisser aucune alerte monter jusqu'au niveau critique.",
    etapes: [
      "Ouvrez le menu **Exploitation**, puis cliquez sur **Alertes**.",
      "Gardez le filtre **Non traitées**.",
      "Lisez le **Type**, ce qu'elle **Concerne** et sa **Priorité**.",
      "Réglez la cause : document, maintenance, stock, sortie de chantier…",
      "Cliquez sur **Vérifier les causes** : l'alerte se ferme seule si sa cause a disparu.",
      "Sinon, cliquez sur **Traiter**, ou sur **Tout traiter** pour un groupe d'alertes.",
    ],
    resultat: "L'alerte quitte la liste « Non traitées » ; dans « Toutes », son statut indique « Traitée » ou « Close auto » avec le motif.",
    bonASavoir: [
      "Documents, entretiens, stock et chantiers : l'alerte se ferme seule quand la cause disparaît (contrôle toutes les 15 minutes).",
      "Survitesse, zones, fatigue, GPS, carburant et incidents restent à traiter à la main.",
      "Une alerte non traitée monte d'un niveau après un délai (7, 3 puis 2 jours par défaut).",
      "Les alertes répétées du même type sont regroupées sur une seule ligne.",
    ],
    schema: "escalade-alertes",
    voirAussi: ["faq-alerte-close-seule", "faq-alerte-monte", "guide-regler-controles"],
  },
  {
    type: "GUIDE",
    id: "guide-suivre-conformite",
    titre: "Suivre la conformité et la fatigue au volant",
    resume: "Voir la part des véhicules et des conducteurs en règle, et les temps de conduite dépassés.",
    revision: "2026-09-29",
    motsCles: ["conformité", "conforme", "document obligatoire", "permis", "caces", "fatigue", "temps de conduite", "pause", "4 h 30", "9 h", "sinistralité"],
    ecrans: ["/fiabilite"],
    capacite: "CONSULTER_GESTION",
    frequence: "HEBDOMADAIRE",
    priorite: "HAUTE",
    objectif: "Atteindre 100 % de véhicules et de conducteurs en règle, et éviter la conduite trop longue.",
    etapes: [
      "Ouvrez **Fiabilité et conformité**, puis l'onglet **Conformité**.",
      "Lisez les taux de véhicules et de conducteurs conformes.",
      "Pour chaque ligne rouge, renouvelez le document, le permis ou le CACES indiqué.",
      "Lisez les dépassements de temps de conduite des 30 derniers jours.",
      "Cliquez sur **Réglages par type** pour choisir les documents obligatoires de chaque type.",
    ],
    resultat: "Vous voyez qui n'est pas en règle et pourquoi ; une mission ne démarre pas tant que le problème reste.",
    bonASavoir: [
      "Sans choix, un type exige l'assurance et la visite technique.",
      "Au démarrage, le permis est exigé pour un véhicule routier, le CACES pour un engin de chantier.",
      "Seuils de fatigue par défaut : 4 h 30 sans pause de 45 min, 9 h par jour ; réglables dans **Paramètres**.",
    ],
    voirAussi: ["depannage-mission-sans-assurance", "guide-volet-sinistre", "guide-traiter-alerte"],
  },
  {
    type: "GUIDE",
    id: "guide-configurer-webhook",
    titre: "Envoyer les alertes critiques vers un autre outil",
    resume: "Transmettre chaque alerte critique à n8n, à une messagerie d'équipe ou à un autre logiciel.",
    revision: "2026-09-29",
    motsCles: ["webhook", "intégration", "n8n", "notification", "alerte critique", "api", "signature", "hmac"],
    ecrans: ["/parametres"],
    capacite: "ADMINISTRER",
    frequence: "OCCASIONNELLE",
    priorite: "BASSE",
    objectif: "Être prévenu hors de l'application quand une alerte critique survient.",
    avantDeCommencer: ["L'outil qui reçoit doit fournir une adresse (URL) de webhook, de préférence en https."],
    etapes: [
      "Ouvrez **Paramètres**, rubrique **Webhooks des alertes critiques**.",
      "Saisissez un **Nom** et l'**Adresse** fournie par l'outil, puis cliquez sur **Ajouter**.",
      "Copiez le **secret** affiché et collez-le dans l'outil qui reçoit : il ne sera plus montré.",
      "Cliquez sur **Tester** et vérifiez la réception dans l'outil.",
    ],
    resultat: "Chaque alerte critique, ou escaladée en critique, part en JSON signé vers l'adresse choisie.",
    bonASavoir: [
      "L'outil qui reçoit vérifie l'en-tête X-ParkAuto-Signature (HMAC-SHA256 de « horodatage.corps » avec le secret).",
      "Trois tentatives en cas d'échec (tout de suite, après 30 secondes, après 2 minutes) ; le détail est dans **Envois**.",
      "Une adresse en http n'est pas chiffrée : à réserver au réseau local.",
    ],
    voirAussi: ["guide-traiter-alerte"],
  },
];
