import type { PageGuide } from "@/types/aide";
import { REVISION_INITIALE } from "@/features/aide/contenu/revision";

/** Guides par tâche — module « Carburant et incidents » (saisies de terrain). */
export const guidesTerrain: PageGuide[] = [
  {
    type: "GUIDE",
    id: "guide-enregistrer-plein",
    titre: "Enregistrer un plein ou un appoint de carburant",
    resume: "Saisir un plein complet, un appoint ou un bidon, avec le kilométrage.",
    revision: REVISION_INITIALE,
    motsCles: ["carburant", "gasoil", "essence", "plein", "appoint", "bidon", "station", "consommation", "litres"],
    ecrans: ["/carburant", "/engins/:id/rapport"],
    capacite: "SAISIE_TERRAIN",
    frequence: "QUOTIDIENNE",
    priorite: "HAUTE",
    objectif: "Suivre la dépense et la consommation de chaque véhicule.",
    avantDeCommencer: ["Avoir le ticket de la station et le kilométrage du compteur."],
    etapes: [
      "Ouvrez le menu **Exploitation**, puis cliquez sur **Carburant**.",
      "Cliquez sur **Nouveau plein**.",
      "Choisissez le **Véhicule**.",
      "Choisissez le **Type** : **Plein complet**, **Appoint** ou **Bidon**.",
      "Saisissez la **Date et heure**, le **Kilométrage**, les **Litres** et le **Prix / litre**.",
      "Cliquez sur **Enregistrer**.",
    ],
    resultat: "La saisie apparaît dans la liste ; la consommation du véhicule est recalculée.",
    bonASavoir: [
      "Le kilométrage est obligatoire, même pour un appoint.",
      "La consommation en L/100 km se calcule d'un plein complet au suivant.",
      "Chaque saisie est comparée à la consommation de référence : un écart trop grand crée une alerte.",
      "Pour un engin de chantier, le champ **Compteur horaire** apparaît : il sert au calcul des heures travaillées.",
    ],
    schema: "plein-a-plein",
    captures: [
      { fichier: "carburant-nouveau-plein-01.png", alt: "Formulaire de saisie de carburant avec le choix Plein complet, Appoint ou Bidon", legende: "Le choix du type de saisie." },
    ],
    voirAussi: ["faq-plein-ou-appoint", "faq-consommation-anormale", "guide-regler-controles"],
  },
  {
    type: "GUIDE",
    id: "guide-declarer-incident",
    titre: "Déclarer un incident ou un accident",
    resume: "Signaler une panne, un accident, un vol ou tout autre problème sur un véhicule.",
    revision: REVISION_INITIALE,
    motsCles: ["accident", "panne", "vol", "sinistre", "casse", "problème", "signaler"],
    ecrans: ["/incidents", "/engins/:id/rapport"],
    capacite: "SAISIE_TERRAIN",
    frequence: "HEBDOMADAIRE",
    priorite: "HAUTE",
    objectif: "Prévenir l'équipe tout de suite et garder une trace du problème.",
    etapes: [
      "Ouvrez le menu **Exploitation**, puis cliquez sur **Incidents**.",
      "Cliquez sur **Déclarer un incident**.",
      "Choisissez le **Véhicule**, le **Type** et la **Gravité**.",
      "Saisissez la **Date de survenue** et une **Description** courte et précise.",
      "Cliquez sur **Déclarer**.",
    ],
    resultat: "L'incident apparaît dans la liste au statut « Déclaré » et dans le rapport du véhicule.",
    bonASavoir: [
      "Choisissez la gravité avec soin : « Élevée » et « Critique » s'affichent en rouge.",
      "Ajoutez un **Coût estimé (optionnel)** si vous le connaissez déjà.",
    ],
    voirAussi: ["guide-cloturer-incident", "guide-consulter-rapport-vehicule"],
  },
  {
    type: "GUIDE",
    id: "guide-cloturer-incident",
    titre: "Clôturer un incident",
    resume: "Fermer un incident traité en laissant un compte rendu.",
    revision: REVISION_INITIALE,
    motsCles: ["fermer incident", "compte rendu", "responsable", "traiter incident"],
    ecrans: ["/incidents"],
    capacite: "GERER_PARC",
    frequence: "HEBDOMADAIRE",
    priorite: "MOYENNE",
    objectif: "Garder l'historique propre et savoir comment chaque incident a été réglé.",
    etapes: [
      "Ouvrez **Incidents**.",
      "Sur la ligne de l'incident, ouvrez le menu **…**, puis cliquez sur **Clôturer**.",
      "Rédigez le **Compte rendu** : ce qui a été fait et le coût final.",
      "Cliquez sur **Clôturer l'incident**.",
    ],
    resultat: "L'incident passe au statut « Clôturé » et ne peut plus être modifié.",
    bonASavoir: [
      "Le compte rendu est obligatoire.",
      "Pour confier le suivi à quelqu'un, utilisez **Assigner un responsable**.",
    ],
    voirAussi: ["guide-declarer-incident", "guide-volet-sinistre"],
  },
  {
    type: "GUIDE",
    id: "guide-volet-sinistre",
    titre: "Compléter le volet sinistre d'un incident",
    resume: "Suivre le dossier chez l'assureur : responsabilité, franchise, indemnisation et reste à charge.",
    revision: "2026-09-29",
    motsCles: ["sinistre", "assurance", "assureur", "dossier", "franchise", "indemnisation", "responsabilité", "reste à charge", "accident", "vol"],
    ecrans: ["/incidents", "/fiabilite"],
    capacite: "GERER_PARC",
    frequence: "OCCASIONNELLE",
    priorite: "MOYENNE",
    objectif: "Savoir ce que coûte vraiment un accident ou un vol une fois l'assurance passée.",
    etapes: [
      "Ouvrez **Incidents** et repérez l'accident ou le vol.",
      "Cliquez sur les trois points de la ligne, puis sur **Volet sinistre (assurance)**.",
      "Saisissez l'assureur, le numéro de dossier et la responsabilité.",
      "Saisissez les dommages, la franchise et l'indemnisation reçue.",
      "Passez le dossier à **Dossier clos** quand l'assureur a réglé.",
      "Cliquez sur **Enregistrer**.",
    ],
    resultat: "Le reste à charge est calculé ; le sinistre apparaît dans l'onglet **Sinistres** et le rapport de sinistralité.",
    bonASavoir: [
      "Dommages laissés vides : le coût estimé de l'incident est utilisé.",
      "Reste à charge = dommages − indemnisation reçue ; il reste provisoire tant que le dossier est ouvert.",
      "Une panne n'est pas un sinistre : le volet n'est pas proposé.",
    ],
    voirAussi: ["guide-cloturer-incident", "guide-suivre-conformite"],
  },
];
