import type { PageGuide } from "@/types/aide";
import { REVISION_INITIALE } from "@/features/aide/contenu/revision";

/** Guides par tâche — module « Véhicules et documents ». */
export const guidesVehicules: PageGuide[] = [
  {
    type: "GUIDE",
    id: "guide-ajouter-vehicule",
    titre: "Ajouter un véhicule au parc",
    resume: "Créer la fiche d'un véhicule routier ou d'un engin de chantier.",
    revision: REVISION_INITIALE,
    motsCles: ["nouveau véhicule", "créer engin", "fiche véhicule", "immatriculation", "camion", "voiture"],
    ecrans: ["/engins", "/engins/nouveau"],
    capacite: "GERER_PARC",
    frequence: "MENSUELLE",
    priorite: "HAUTE",
    objectif: "Enregistrer un nouveau véhicule en quelques minutes pour pouvoir le suivre.",
    avantDeCommencer: [
      "Avoir le rôle Directeur général ou Responsable du parc.",
      "Vérifier que le type de véhicule existe dans **Types de véhicule**.",
    ],
    etapes: [
      "Ouvrez le menu **Parc**, puis cliquez sur **Véhicules**.",
      "Cliquez sur **Nouveau véhicule**.",
      "Choisissez le **Type de véhicule**.",
      "Saisissez l'**Immatriculation**, ou le **Numéro de série** pour un engin de chantier.",
      "Complétez la **Marque**, le **Modèle** et le compteur de départ.",
      "Ajoutez une photo du véhicule si vous en avez une.",
      "Cliquez sur **Créer le véhicule**.",
    ],
    resultat: "Le véhicule apparaît dans la liste des véhicules, prêt pour des missions.",
    bonASavoir: [
      "L'immatriculation, ou le numéro de série, doit être unique dans tout le parc.",
      "Le code interne est attribué automatiquement ; il n'est pas affiché.",
    ],
    schema: "statuts-vehicule",
    captures: [
      { fichier: "vehicules-nouveau-vehicule-01.png", alt: "Liste des véhicules avec le bouton Nouveau véhicule en haut à droite", legende: "Le bouton « Nouveau véhicule »." },
      { fichier: "vehicules-fiche-02.png", alt: "Fiche d'un nouveau véhicule avec le type, l'immatriculation, la marque et le modèle", legende: "Les champs à remplir." },
    ],
    voirAussi: ["guide-enregistrer-document", "guide-installer-boitier-gps", "reference-vehicules"],
  },
  {
    type: "GUIDE",
    id: "guide-mettre-a-jour-kilometrage",
    titre: "Mettre à jour le kilométrage d'un véhicule",
    resume: "Corriger ou avancer le compteur d'un véhicule hors mission et hors plein.",
    revision: REVISION_INITIALE,
    motsCles: ["compteur", "km", "kilomètres", "odomètre", "heures moteur"],
    ecrans: ["/engins"],
    capacite: "SAISIE_TERRAIN",
    frequence: "HEBDOMADAIRE",
    priorite: "MOYENNE",
    objectif: "Garder un compteur juste pour l'entretien et la consommation.",
    etapes: [
      "Ouvrez **Véhicules**.",
      "Sur la ligne du véhicule, ouvrez le menu **…**.",
      "Cliquez sur **Mettre à jour le kilométrage**.",
      "Saisissez le **Nouveau kilométrage**.",
      "Cliquez sur **Valider**.",
    ],
    resultat: "Le nouveau compteur s'affiche dans la liste et dans le rapport du véhicule.",
    bonASavoir: [
      "Le kilométrage ne peut jamais baisser : une valeur inférieure est refusée.",
      "Une mission terminée et un plein mettent aussi le compteur à jour.",
    ],
    voirAussi: ["depannage-kilometrage-inferieur", "guide-enregistrer-plein"],
  },
  {
    type: "GUIDE",
    id: "guide-consulter-rapport-vehicule",
    titre: "Consulter le rapport d'un véhicule",
    resume: "Voir en un coup d'œil l'état d'un véhicule : entretien, documents, carburant, incidents, localisation.",
    revision: REVISION_INITIALE,
    motsCles: ["état véhicule", "fiche", "infographie", "voir", "situation", "localisation", "gps"],
    ecrans: ["/engins", "/engins/:id/rapport", "/engins/:id/historique"],
    frequence: "QUOTIDIENNE",
    priorite: "HAUTE",
    objectif: "Savoir immédiatement ce qui demande une action sur un véhicule.",
    etapes: [
      "Ouvrez **Véhicules**.",
      "Sur la ligne du véhicule, ouvrez le menu **…**, puis cliquez sur **Voir le rapport**.",
      "Lisez la couleur de chaque carte : vert, jaune ou rouge.",
      "Regardez la carte **Localisation** pour savoir où est le véhicule.",
      "Cliquez sur **Voir le détail** pour consulter l'historique d'une carte.",
    ],
    resultat: "Vous savez ce qui est en ordre et ce qui doit être traité.",
    bonASavoir: [
      "Vert : situation normale. Jaune : à surveiller. Rouge : action nécessaire. Gris : information manquante.",
      "Les boutons des cartes ouvrent directement l'action : **Faire la maintenance**, **Ajouter un plein**, **Déclarer un incident**.",
    ],
    captures: [
      { fichier: "vehicules-rapport-01.png", alt: "Rapport d'un véhicule : photo au centre et six cartes colorées autour", legende: "Le rapport d'un véhicule." },
    ],
    voirAussi: ["guide-suivre-vehicule-carte", "guide-creer-maintenance", "faq-couleurs-rapport"],
  },
  {
    type: "GUIDE",
    id: "guide-enregistrer-document",
    titre: "Enregistrer une assurance ou une visite technique",
    resume: "Ajouter un document administratif à un véhicule ou à un conducteur, avec sa date d'expiration.",
    revision: REVISION_INITIALE,
    motsCles: ["document", "assurance", "visite technique", "carte grise", "permis", "expiration", "renouveler"],
    ecrans: ["/documents"],
    capacite: "GERER_PARC",
    frequence: "MENSUELLE",
    priorite: "HAUTE",
    objectif: "Suivre les échéances et éviter qu'un véhicule roule sans documents valides.",
    avantDeCommencer: ["Avoir sous la main le numéro et les dates du document."],
    etapes: [
      "Ouvrez le menu **Parc**, puis cliquez sur **Documents**.",
      "Cliquez sur **Nouveau document**.",
      "Choisissez le **Type** : Assurance, Visite technique, Carte grise…",
      "Choisissez le **Véhicule (facultatif)** ou le **Conducteur (facultatif)** concerné.",
      "Saisissez le **Numéro de référence**, la **Date de début** et la **Date d'expiration**.",
      "Cliquez sur **Créer**.",
    ],
    resultat: "Le document apparaît dans la liste ; la carte Documents du rapport du véhicule se met à jour.",
    bonASavoir: [
      "Sans assurance ni visite technique valides, une mission ne peut pas démarrer.",
      "Pour un renouvellement, utilisez **Remplacer le document** : l'ancien reste dans l'historique.",
      "Un document qui expire sous 30 jours déclenche une alerte.",
    ],
    voirAussi: ["depannage-mission-sans-assurance", "guide-traiter-alerte"],
  },
  {
    type: "GUIDE",
    id: "guide-planifier-renouvellement",
    titre: "Planifier le renouvellement et sortir un véhicule du parc",
    resume: "Savoir quand remplacer chaque véhicule, combien il en faudra, et enregistrer une vente ou une réforme.",
    revision: "2026-09-29",
    motsCles: ["renouvellement", "remplacer", "âge moyen", "besoins futurs", "vente", "réforme", "cession", "valeur nette", "plus-value", "moins-value", "électrique", "hybride"],
    ecrans: ["/renouvellement"],
    capacite: "CONSULTER_GESTION",
    frequence: "OCCASIONNELLE",
    priorite: "MOYENNE",
    objectif: "Préparer le budget de remplacement et suivre ce que rapportent les véhicules sortis.",
    etapes: [
      "Ouvrez le menu **Pilotage**, puis cliquez sur **Renouvellement**.",
      "Dans **Plan de renouvellement**, lisez les véhicules **Cette année** et **L'an prochain**.",
      "Lisez le budget de remplacement par année.",
      "Ouvrez **Besoins futurs** pour voir les types à acquérir ou en surplus.",
      "Dans **Fin de vie**, cliquez sur **Sortir un véhicule du parc** pour une vente ou une réforme.",
      "Cliquez sur **Rapport PDF** pour garder le plan.",
    ],
    resultat: "Le plan donne l'année de remplacement de chaque véhicule ; un véhicule sorti passe au statut « Vendu » ou « Réformé ».",
    bonASavoir: [
      "Les seuils d'âge et de compteur sont ceux des véhicules à remplacer (**Paramètres**).",
      "La valeur nette et la plus-value ou moins-value proviennent de la rubrique **Coûts** de la fiche.",
      "Le mode d'acquisition se saisit dans la rubrique **Coûts** ; l'énergie, dans la fiche technique.",
    ],
    voirAussi: ["guide-suivre-fiabilite", "guide-suivre-couts-complets", "guide-saisir-couts-vehicule"],
  },
  {
    type: "GUIDE",
    id: "guide-importer-excel",
    titre: "Importer des véhicules, conducteurs ou pleins depuis Excel",
    resume: "Reprendre une liste existante ou un relevé de carte carburant sans ressaisie.",
    revision: "2026-09-29",
    motsCles: ["import", "importer", "excel", "csv", "fichier", "reprise", "carte carburant", "relevé", "modèle", "liste"],
    ecrans: ["/imports"],
    capacite: "GERER_PARC",
    frequence: "OCCASIONNELLE",
    priorite: "MOYENNE",
    objectif: "Charger en une seule fois des dizaines de fiches ou de pleins, avec les mêmes contrôles qu'à l'écran.",
    etapes: [
      "Ouvrez le menu **Administration**, puis cliquez sur **Import Excel ou CSV**.",
      "Choisissez **Véhicules**, **Conducteurs** ou **Pleins de carburant**.",
      "Cliquez sur **Télécharger le modèle** et remplissez-le, une ligne par élément.",
      "Cliquez sur **Choisir le fichier** : l'aperçu vérifie chaque ligne sans rien enregistrer.",
      "Corrigez les lignes en **Erreur** dans le fichier, puis choisissez-le de nouveau.",
      "Lorsqu'il ne reste aucune erreur, cliquez sur **Importer**.",
    ],
    resultat: "Toutes les lignes sont enregistrées en une seule opération ; s'il reste une erreur, rien n'est enregistré.",
    bonASavoir: [
      "L'ordre des colonnes n'a pas d'importance ; les titres du modèle et leurs variantes courantes sont reconnus.",
      "Un plein « À vérifier » (distance impossible, saisie antidatée) est importé avec une alerte « Saisie à vérifier ».",
      "Un plein dont le kilométrage est inférieur au compteur actuel est accepté sans faire reculer le compteur.",
      "Au plus 2 000 lignes et 5 Mo par fichier ; enregistrez au préalable tout fichier .xls au format .xlsx depuis Excel.",
    ],
    voirAussi: ["guide-ajouter-vehicule", "guide-enregistrer-plein"],
  },
];
