import type { PageDepannage, SectionAide } from "@/types/aide";
import { REVISION_INITIALE } from "@/features/aide/contenu/revision";

/**
 * Dépannage (étape 4, modèle fixe) : symptôme avec le texte exact du message,
 * cause probable, solution en étapes. « Si le problème continue » est commun
 * à toutes les entrées (voir PageDepannage dans l'écran). Messages recopiés
 * du serveur (BusinessRuleException, GlobalExceptionHandler) et de api-client.ts.
 */
function d(entree: Omit<PageDepannage, "type" | "revision">): PageDepannage {
  return { type: "DEPANNAGE", revision: REVISION_INITIALE, ...entree };
}

export const themesDepannage: SectionAide[] = [
  {
    id: "depannage-connexion",
    titre: "Connexion et accès",
    icone: "Shield",
    pages: [
      d({
        id: "depannage-identifiants",
        titre: "Je ne parviens pas à me connecter",
        resume: "Le message « Email ou mot de passe incorrect » s'affiche.",
        symptome: "La page de connexion refuse l'accès.",
        message: "Email ou mot de passe incorrect",
        cause: "L'adresse électronique ou le mot de passe est mal saisi, ou le mot de passe a changé.",
        solution: [
          "Vérifiez que le verrouillage des majuscules n'est pas activé.",
          "Saisissez à nouveau l'adresse électronique complète, sans espace à la fin.",
          "Si l'erreur persiste, demandez un nouveau mot de passe à l'administrateur.",
        ],
        motsCles: ["connexion", "refusé", "mot de passe", "incorrect"],
        ecrans: ["/connexion"],
        voirAussi: ["faq-mot-de-passe-oublie"],
      }),
      d({
        id: "depannage-compte-desactive",
        titre: "Mon compte est désactivé",
        resume: "Le message « Compte désactivé » s'affiche à la connexion.",
        symptome: "La connexion est refusée même avec le bon mot de passe.",
        message: "Compte désactivé",
        cause: "Un administrateur a désactivé votre compte.",
        solution: ["Contactez l'administrateur ou votre responsable pour le faire réactiver."],
        motsCles: ["désactivé", "bloqué", "compte"],
        ecrans: ["/connexion"],
      }),
      d({
        id: "depannage-session-expiree",
        titre: "Je suis renvoyé vers la page de connexion",
        resume: "L'application revient à la page de connexion en cours de travail.",
        symptome: "Après une pause, un clic ramène à la page de connexion.",
        cause: "Votre session a expiré pour votre sécurité.",
        solution: ["Reconnectez-vous.", "Refaites la dernière action : elle n'a pas été enregistrée."],
        motsCles: ["session", "expirée", "déconnecté", "renvoyé"],
      }),
      d({
        id: "depannage-acces-refuse",
        titre: "Une action est refusée pour mon rôle",
        resume: "Le message « Rôle insuffisant pour cette action » s'affiche.",
        symptome: "Un bouton affiche une erreur, ou une page indique « Accès refusé ».",
        message: "Rôle insuffisant pour cette action",
        cause: "Votre rôle ne permet pas cette action.",
        solution: ["Consultez la page sur les rôles.", "Demandez à la personne compétente de réaliser l'action, ou demandez un changement de rôle."],
        motsCles: ["accès refusé", "403", "interdit", "droits"],
        voirAussi: ["demarrer-roles"],
      }),
      d({
        id: "depannage-trop-de-tentatives",
        titre: "« Trop de tentatives de connexion »",
        resume: "Plusieurs mots de passe erronés ont bloqué la connexion pendant 15 minutes.",
        symptome: "La connexion est refusée même avec le bon mot de passe.",
        message: "Trop de tentatives de connexion. Réessayez dans 15 minutes.",
        cause: "5 échecs sur le même compte, ou 20 depuis le même poste, en 15 minutes.",
        solution: ["Attendez 15 minutes, puis reconnectez-vous.", "En cas d'oubli, demandez un nouveau mot de passe à l'administrateur."],
        motsCles: ["tentatives", "bloqué", "429", "connexion", "verrouillé"],
        voirAussi: ["faq-mot-de-passe-oublie"],
      }),
      d({
        id: "depannage-mot-de-passe-refuse",
        titre: "Le nouveau mot de passe est refusé",
        resume: "Le mot de passe choisi ne respecte pas la politique de sécurité.",
        symptome: "Le changement, la réinitialisation ou la création du compte affiche « Mot de passe refusé ».",
        message: "Mot de passe refusé : …",
        cause: "Moins de 12 caractères, mot trop courant, suite évidente, ou présence du nom, du prénom ou de l'adresse électronique.",
        solution: ["Choisissez une courte phrase personnelle, par exemple « le zébu traverse la RN7 ».", "Évitez « azerty », « 1234… » et le nom de l'entreprise."],
        motsCles: ["mot de passe", "refusé", "trop court", "politique", "sécurité"],
        voirAussi: ["faq-changer-mot-de-passe"],
      }),
      d({
        id: "depannage-serveur-injoignable",
        titre: "L'application ne parvient pas à contacter le serveur",
        resume: "Le message « Impossible de contacter le serveur » s'affiche.",
        symptome: "Les pages restent vides ou affichent une erreur de chargement.",
        message: "Impossible de contacter le serveur. Vérifiez qu'il est démarré et accessible.",
        cause: "Le réseau est coupé, ou le serveur est arrêté.",
        solution: [
          "Vérifiez votre connexion Internet ou Wi-Fi.",
          "Rechargez la page avec la touche F5.",
          "Si l'erreur persiste pour tout le monde, prévenez l'administrateur.",
        ],
        motsCles: ["serveur", "réseau", "hors ligne", "chargement", "erreur"],
      }),
    ],
  },
  {
    id: "depannage-missions",
    titre: "Missions",
    icone: "Route",
    pages: [
      d({
        id: "depannage-mission-sans-assurance",
        titre: "Le démarrage de la mission est refusé (document, permis ou CACES)",
        resume: "Le démarrage est refusé : document du véhicule, permis ou CACES du conducteur non valide.",
        symptome: "Le démarrage de la mission affiche une erreur.",
        message: "Le véhicule « … » n'a pas d'assurance valide : la mission ne peut pas démarrer (règle 11.20).",
        cause: "Un document obligatoire du type de véhicule manque ou a expiré, ou le conducteur n'a pas de permis (véhicule routier) ou de CACES (engin) valide.",
        solution: [
          "Lisez le message : il nomme le document, le permis ou le CACES en cause.",
          "Pour un document, ouvrez **Documents** et enregistrez la version à jour.",
          "Pour le conducteur, mettez à jour la date d'expiration dans **Conducteurs**, ou choisissez un autre conducteur.",
          "Démarrez de nouveau la mission.",
        ],
        motsCles: ["démarrer", "assurance", "visite technique", "11.20", "11.21", "permis", "caces", "document obligatoire", "conformité"],
        ecrans: ["/missions"],
        voirAussi: ["guide-enregistrer-document", "guide-suivre-conformite"],
      }),
      d({
        id: "depannage-conducteur-occupe",
        titre: "Le conducteur a déjà une mission sur cette période",
        resume: "La création ou le démarrage est refusé car le conducteur est déjà pris.",
        symptome: "L'enregistrement de la mission est refusé.",
        message: "Le conducteur « … » a déjà une mission active sur cette période (règle 3.6)",
        cause: "Le conducteur a déjà une mission planifiée ou en cours qui chevauche ces dates.",
        solution: ["Ouvrez **Missions** et repérez la mission qui se chevauche.", "Changez les dates, ou choisissez un autre conducteur."],
        motsCles: ["conducteur", "chevauchement", "déjà", "3.6"],
        ecrans: ["/missions"],
      }),
      d({
        id: "depannage-vehicule-indisponible",
        titre: "Le véhicule n'est pas disponible",
        resume: "Le véhicule choisi est en panne, en maintenance ou déjà en mission.",
        symptome: "L'enregistrement est refusé à cause du statut du véhicule.",
        message: "L'engin « … » n'est pas disponible (statut actuel : …)",
        cause: "Le véhicule est en panne, en maintenance, en mission, réformé ou vendu.",
        solution: ["Ouvrez le rapport du véhicule pour voir son statut.", "Choisissez un autre véhicule, ou attendez la fin de la maintenance."],
        motsCles: ["indisponible", "statut", "en panne", "en maintenance"],
        ecrans: ["/missions", "/affectations"],
      }),
      d({
        id: "depannage-kilometrage-retour",
        titre: "Le kilométrage au retour est refusé",
        resume: "Le kilométrage saisi au retour est inférieur à celui du départ.",
        symptome: "La fin de mission affiche une erreur de kilométrage.",
        message: "Le kilométrage de retour (…) ne peut pas être inférieur au kilométrage de départ (…)",
        cause: "Une faute de frappe, ou un kilométrage de départ mal saisi.",
        solution: ["Relisez le compteur du véhicule.", "Saisissez un kilométrage au retour supérieur ou égal à celui du départ."],
        motsCles: ["kilométrage", "retour", "inférieur"],
        ecrans: ["/missions"],
      }),
    ],
  },
  {
    id: "depannage-saisies",
    titre: "Saisies refusées",
    icone: "TriangleAlert",
    pages: [
      d({
        id: "depannage-kilometrage-inferieur",
        titre: "Le nouveau kilométrage est refusé",
        resume: "Le kilométrage saisi est inférieur à celui déjà enregistré.",
        symptome: "La mise à jour du compteur, ou un plein, affiche une erreur.",
        message: "Le kilométrage (…) ne peut pas être inférieur au kilométrage actuel (…)",
        cause: "Le compteur ne peut pas reculer : la valeur saisie est inférieure à la dernière valeur connue.",
        solution: [
          "Relisez le compteur du véhicule.",
          "Si la dernière valeur enregistrée est erronée, demandez sa correction au responsable du parc.",
        ],
        motsCles: ["kilométrage", "compteur", "inférieur", "reculer"],
        ecrans: ["/engins", "/carburant"],
      }),
      d({
        id: "depannage-plein-refuse",
        titre: "Le plein est refusé ou demande une confirmation",
        resume: "La saisie paraît impossible ou incohérente avec les pleins précédents du véhicule.",
        symptome: "L'enregistrement est refusé, ou une fenêtre « Saisie à vérifier » s'ouvre.",
        message: "La quantité (…) dépasse la capacité du réservoir / Cette saisie semble déjà enregistrée",
        cause: "Quantité supérieure à la capacité du réservoir, plein déjà saisi, ou distance impossible depuis le plein précédent.",
        solution: [
          "Relisez les litres, la date et le compteur sur le ticket.",
          "Si la saisie est exacte, cliquez sur **Enregistrer quand même** : le responsable reçoit une alerte.",
          "Si la capacité du réservoir est erronée, corrigez la fiche du véhicule.",
        ],
        motsCles: ["plein", "refusé", "réservoir", "doublon", "à vérifier", "vitesse impossible"],
        ecrans: ["/carburant"],
        voirAussi: ["guide-enregistrer-plein"],
      }),
      d({
        id: "depannage-date-maintenance-passee",
        titre: "La date prévue d'une maintenance est refusée",
        resume: "La date choisie pour une maintenance est dans le passé.",
        symptome: "La planification ou la replanification affiche une erreur.",
        message: "La date prévue d'une maintenance ne peut pas être dans le passé",
        cause: "La date choisie est antérieure à aujourd'hui.",
        solution: ["Choisissez une date à partir d'aujourd'hui.", "Pour une intervention déjà effectuée, choisissez **Commencer maintenant** puis terminez-la."],
        motsCles: ["date", "passé", "maintenance", "planifier"],
        ecrans: ["/maintenance"],
      }),
      d({
        id: "depannage-terminer-bloque",
        titre: "Le bouton « Terminer » d'une maintenance reste grisé",
        resume: "La maintenance chez un garage externe attend sa facture pro forma.",
        symptome: "Dans la fenêtre « Terminer la maintenance », le bouton **Terminer** ne répond pas.",
        cause: "La maintenance est confiée à un garage externe et aucune facture pro forma n'est jointe.",
        solution: ["Joignez la **Facture pro forma du garage externe** (PDF ou photo).", "Cliquez sur **Terminer**."],
        motsCles: ["terminer", "grisé", "bloqué", "proforma"],
        ecrans: ["/maintenance"],
        voirAussi: ["guide-terminer-maintenance"],
      }),
      d({
        id: "depannage-immatriculation-existe",
        titre: "L'immatriculation existe déjà",
        resume: "Un autre véhicule porte déjà cette immatriculation ou ce numéro de série.",
        symptome: "La création du véhicule est refusée.",
        message: "L'immatriculation « … » existe déjà",
        cause: "Le véhicule est déjà enregistré, ou une faute de frappe désigne un autre véhicule.",
        solution: ["Cherchez l'immatriculation dans **Véhicules**.", "Si le véhicule existe, modifiez sa fiche au lieu d'en créer une nouvelle."],
        motsCles: ["immatriculation", "doublon", "existe déjà", "numéro de série"],
        ecrans: ["/engins/nouveau"],
      }),
    ],
  },
  {
    id: "depannage-affichage",
    titre: "Affichage et GPS",
    icone: "MapPin",
    pages: [
      d({
        id: "depannage-pas-de-position",
        titre: "La carte Localisation n'affiche pas de position",
        resume: "Le rapport du véhicule indique « aucune position » ou « non équipé de GPS ».",
        symptome: "À la place de la carte, un message indique qu'il n'y a pas de position en direct.",
        message: "Véhicule non équipé de GPS : pas de position en direct.",
        cause: "Le véhicule n'a pas de boîtier, son boîtier est inactif ou hors service, ou il n'a encore rien envoyé.",
        solution: [
          "Vérifiez dans **GPS et trajets**, onglet **Dispositifs**, l'état du boîtier.",
          "Réactivez le boîtier, ou installez-en un.",
          "Si le boîtier est actif, vérifiez qu'il est alimenté et qu'il capte le réseau.",
        ],
        motsCles: ["gps", "position", "localisation", "carte vide"],
        ecrans: ["/engins/:id/rapport", "/gps"],
        voirAussi: ["guide-installer-boitier-gps"],
      }),
    ],
  },
];
